"""
Build the HERALD Observatory v0.5.1 narrative presentation-layer exports.

v0.5.1 corrects v0.5 (OBSERVATORY_V05_PARTIAL — see
reports/HERALD_OBSERVATORY_V051_CORRECTION_AUDIT.md for the point-by-point
critique). This module does NOT recompute, alter, or re-derive any
scientific decision, number, or label coming from the v0.4 granular exports.
It is a re-shaping / French-translation layer, EXCEPT for one addition: it
also loads and integrates the PT municipal prediction layer built by
`build_pt_municipal_prediction_layer.py` (causal persistence/Ridge AR(1) on
the observed PT municipal panel — no proxy, no HPC), closing the gap
documented in HERALD_OBSERVATORY_V05_PREDICTION_GAP.md.

Hard rules enforced here (must not regress from v0.5):
  - NL gemeente proxy (region_system=GEMEENTE_PROXY) NEVER enters
    relation_view / the main sector-to-sector graph dataset. It may only
    appear in territory_view, always carrying evidence_badge="Proxy
    territorial".
  - blocked_proxy_edges.csv (121 rows) is kept in its own file/dataset,
    never merged into relation_view, never framed as validated.
  - PT KZ is marked structural_absent explicitly ("Donnée insuffisante" /
    a dedicated French sentence), never a bare NaN.
  - No raw "NaN" string is ever written into a *_view.csv/json human-facing
    field.
  - No causal language ("causal", "causes", "not proof of causality") is
    generated by this script anywhere outside of the methodological-details
    payload, and even there, causality is only ever framed as an explicit
    prohibition.
  - All human-facing text fields are in French.
  - Prediction layer now covers FR, NL, AND PT (municipal grain, integrated
    here, not a separate untouched panel).

Outputs (data/processed/herald_observatory_v051_narrative/):
  - territory_view.csv / .json
  - sector_view.csv / .json
  - relation_view.csv / .json
  - prediction_view.csv / .json   (FR + NL + PT municipal, unified schema)
  - pt_municipal_prediction_view.csv  (already built by the dedicated script;
    copied here verbatim as part of this builder's run for a single
    manifest/checksum source)
  - map_state_by_year_sector.json
  - relation_timeline.json
  - manifest.json
"""
from __future__ import annotations

import hashlib
import json
import logging
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger(__name__)

REPO_ROOT = Path(__file__).resolve().parents[3]
V04_DIR = REPO_ROOT / "data/processed/herald_observatory_v04_granular"
TERRITORY_PATH = V04_DIR / "granular_territory_state_panel.csv"
RELATION_PATH = V04_DIR / "granular_relation_edges.csv"
BLOCKED_PATH = V04_DIR / "blocked_proxy_edges.csv"
V04_MANIFEST_PATH = V04_DIR / "manifest.json"

V03_PANEL_PATH = REPO_ROOT / "data/processed/herald_observatory_v03/herald_observatory_v03_panel.csv"

OUT_DIR = REPO_ROOT / "data/processed/herald_observatory_v051_narrative"
PT_MUNICIPAL_PREDICTION_PATH = OUT_DIR / "pt_municipal_prediction_view.csv"
PT_MUNICIPAL_BUILDER = Path(__file__).resolve().parent / "build_pt_municipal_prediction_layer.py"

# Part F — French, human-readable sector names; A10 code kept separately for
# the small-parenthetical display the dashboard renders next to the name.
SECTOR_LABELS_FR = {
    "BE": "Industrie et énergie",
    "FZ": "Construction",
    "GI": "Commerce, transport et hébergement",
    "JZ": "Information et communication",
    "KZ": "Finance et assurance",
    "LZ": "Immobilier",
    "MN": "Services professionnels",
    "OQ": "Administration, éducation et santé",
    "RU": "Culture et autres services",
}
SECTORS_ORDER = list(SECTOR_LABELS_FR.keys())

# Part I — controlled French vocabulary, never a bare NaN to a layperson.
NO_DATA = "Donnée insuffisante"
PT_KZ_ABSENT = "Secteur non disponible pour le Portugal"
PROXY_CONTEXT = "Proxy territorial (contexte uniquement)"
INSUFFICIENT = "Donnée insuffisante"
STRUCTURAL_ABSENT_LABEL = "Absence structurelle"

STATE_NUM = {"DECLINE": -1, "STAGNATION": 0, "GROWTH": 1}
STATE_LABEL_HUMAN_FR = {1: "Croissance", 0: "Stable", -1: "Recul", None: NO_DATA}

# region_system that matches v0.4 granular grain <-> v0.3 forecast grain for
# FR/NL. PT is handled separately via the dedicated municipal forecast.
PREDICTION_JOINABLE_SYSTEMS = {"ZE2020", "COROP"}


def _sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def _atomic_write_text(path: Path, text: str) -> None:
    tmp = Path(str(path) + ".tmp")
    tmp.write_text(text, encoding="utf-8")
    tmp.replace(path)


def _atomic_write_df_csv(df: pd.DataFrame, path: Path) -> None:
    tmp = Path(str(path) + ".tmp")
    df.to_csv(tmp, index=False)
    tmp.replace(path)


def ensure_pt_municipal_prediction() -> pd.DataFrame:
    """Builds (if missing or stale) and loads the PT municipal prediction
    layer. Runs the dedicated builder as a subprocess so this export script
    and the PT forecast builder remain independently testable/runnable."""
    if not PT_MUNICIPAL_PREDICTION_PATH.exists():
        logger.info("PT municipal prediction view missing — building it now")
        subprocess.run([sys.executable, str(PT_MUNICIPAL_BUILDER)], check=True, cwd=str(REPO_ROOT))
    df = pd.read_csv(PT_MUNICIPAL_PREDICTION_PATH, low_memory=False)
    return df


def load_sources() -> dict:
    territory = pd.read_csv(TERRITORY_PATH, low_memory=False)
    relation = pd.read_csv(RELATION_PATH)
    blocked = pd.read_csv(BLOCKED_PATH)
    v04_manifest = json.loads(V04_MANIFEST_PATH.read_text())

    # Fail-closed invariants inherited from v0.4/v0.5 — re-asserted here.
    assert "GEMEENTE_PROXY" not in relation["region_system"].values, \
        "FAIL_CLOSED: NL gemeente proxy must never appear in relation edges (v0.5.1 narrative)"
    assert (blocked["allowed_for_training_label"] == False).all(), \
        "FAIL_CLOSED: blocked proxy edges must have allowed_for_training_label=false"

    forecast = None
    if V03_PANEL_PATH.exists():
        forecast = pd.read_csv(V03_PANEL_PATH, low_memory=False)
    else:
        logger.warning("v0.3 panel not found at %s — FR/NL prediction layer will be empty", V03_PANEL_PATH)

    pt_municipal_forecast = ensure_pt_municipal_prediction()

    return {
        "territory": territory, "relation": relation, "blocked": blocked,
        "v04_manifest": v04_manifest, "forecast": forecast,
        "pt_municipal_forecast": pt_municipal_forecast,
    }


def human_state_fr(state_str) -> str:
    if pd.isna(state_str):
        return NO_DATA
    return {"GROWTH": "Croissance", "DECLINE": "Recul", "STAGNATION": "Stable",
            "INSUFFICIENT_DATA": NO_DATA}.get(state_str, NO_DATA)


def evidence_badge_for_territory_row(row) -> str:
    if row["evidence_type"] == "proxy_disaggregated_by_stock_share":
        return PROXY_CONTEXT
    return "Observé"


def build_territory_view(territory: pd.DataFrame) -> pd.DataFrame:
    df = territory.copy()
    df["region_name"] = df["region_name"].fillna(df["region_id"].astype(str))
    df["sector_name"] = df["sector_a10"].map(SECTOR_LABELS_FR)
    df["state_human"] = df["state"].apply(human_state_fr)
    df["evidence_badge"] = df.apply(evidence_badge_for_territory_row, axis=1)
    df["is_proxy_context"] = df["evidence_type"].eq("proxy_disaggregated_by_stock_share")

    # PT structural_absent KZ (DEC-064/DEC-018).
    pt_kz_mask = df["country"].eq("PT") & df["sector_a10"].eq("KZ")
    if pt_kz_mask.any():
        df.loc[pt_kz_mask, "state_human"] = PT_KZ_ABSENT
        df.loc[pt_kz_mask, "evidence_badge"] = STRUCTURAL_ABSENT_LABEL

    out_cols = [
        "country", "region_id", "region_name", "region_system", "year",
        "sector_a10", "sector_name", "value", "state", "state_human",
        "velocity", "evidence_type", "evidence_badge", "is_proxy_context",
        "source_table", "allowed_use",
    ]
    return df[out_cols]


def pt_kz_structural_absent_flag(territory: pd.DataFrame) -> bool:
    pt_kz = territory[(territory["country"] == "PT") & (territory["sector_a10"] == "KZ")]
    if len(pt_kz) == 0:
        return True
    return bool(pt_kz["value"].isna().all())


def build_relation_view(relation: pd.DataFrame) -> pd.DataFrame:
    df = relation.copy()
    assert "GEMEENTE_PROXY" not in df["region_system"].values
    df["source_sector_name"] = df["source_sector"].map(SECTOR_LABELS_FR)
    df["target_sector_name"] = df["target_sector"].map(SECTOR_LABELS_FR)
    df["direction_human"] = df["sign"].map({
        "+": "évolue dans la même direction que",
        "-": "évolue dans la direction opposée à",
    })
    df["window_start"] = df["window"].str.split("-").str[0].astype(int)
    df["window_end"] = df["window"].str.split("-").str[1].astype(int)

    evidence_badge_map = {
        "ROBUST_ORIGINAL": "Validé",
        "FINE_GRAIN_SUPPORTED": "Supporté",
        "EXPLORATORY_FINE_GRAIN": "Exploratoire",
    }
    df["evidence_badge"] = df["label_class"].map(evidence_badge_map).fillna(INSUFFICIENT)

    group_cols = ["country", "source_sector", "target_sector"]
    counts = df.groupby(group_cols)["window"].nunique().rename("n_windows")
    signs = df.groupby(group_cols)["sign"].nunique().rename("n_distinct_signs")
    df = df.merge(counts, on=group_cols, how="left").merge(signs, on=group_cols, how="left")
    df["is_recurring"] = df["n_windows"] >= 2
    df["sign_changes"] = df["n_distinct_signs"] >= 2
    df = df.drop(columns=["n_distinct_signs"])

    def sentence(row) -> str:
        # Part F / Part L: predictive-precedence language, never "causal".
        return (
            f"Entre {row['window_start']} et {row['window_end']}, au "
            f"{row['country']}, le secteur {row['source_sector_name']} ({row['source_sector']}) "
            f"semble précéder le secteur {row['target_sector_name']} ({row['target_sector']}) "
            f"et {row['direction_human']} celui-ci. Il s'agit d'une association temporelle "
            f"observée, qui ne constitue pas une recommandation automatique."
        )
    df["plain_sentence"] = df.apply(sentence, axis=1)
    return df


def build_sector_view(territory: pd.DataFrame) -> pd.DataFrame:
    df = territory.copy()
    df["state_num"] = df["state"].map(STATE_NUM)
    grp = df.groupby(["country", "sector_a10", "year"], as_index=False).agg(
        n_territories=("region_id", "nunique"),
        n_growth=("state_num", lambda s: (s == 1).sum()),
        n_decline=("state_num", lambda s: (s == -1).sum()),
        n_stable=("state_num", lambda s: (s == 0).sum()),
        n_no_data=("state_num", lambda s: s.isna().sum()),
        mean_velocity=("velocity", "mean"),
    )
    grp["sector_name"] = grp["sector_a10"].map(SECTOR_LABELS_FR)
    grp["structural_absent"] = False
    pt_kz_mask = grp["country"].eq("PT") & grp["sector_a10"].eq("KZ")
    grp.loc[pt_kz_mask, "structural_absent"] = True
    return grp


def build_fr_nl_prediction_layer(forecast: pd.DataFrame | None) -> pd.DataFrame:
    """FR ZE2020 / NL COROP observed-vs-expected, unchanged method from
    v0.5, re-labelled in French and conformed to the unified schema shared
    with the PT municipal prediction rows."""
    cols = [
        "country", "region_id", "region_system", "sector_a10", "sector_name",
        "year", "observed_value", "expected_value", "difference",
        "trend_state", "forecast_method", "forecast_status",
        "forecast_evidence_tier", "available",
    ]
    if forecast is None:
        return pd.DataFrame(columns=cols)
    df = forecast[forecast["region_system"].isin(PREDICTION_JOINABLE_SYSTEMS)].copy()
    df["expected_value"] = df["ridge_forecast"]
    df["expected_value"] = df["expected_value"].fillna(df["persistence_forecast"])
    df["difference"] = df["observed_value"] - df["expected_value"]
    state_map = {"growth": "Croissance", "decline": "Recul", "stagnation": "Stable",
                 "acceleration": "Croissance", "deceleration": "Croissance",
                 "recovery": "Croissance", "insufficient_history": NO_DATA}
    df["trend_state"] = df["economic_state"].map(state_map).fillna(NO_DATA)
    df["available"] = df["expected_value"].notna()
    df["forecast_status"] = df["available"].map({True: "valid_forecast", False: "insufficient_history"})
    out = df[[
        "country", "territory_id", "region_system", "sector_id", "sector_label",
        "observation_year", "observed_value", "expected_value", "difference",
        "trend_state", "forecast_method", "forecast_evidence_tier", "available",
        "forecast_status",
    ]].rename(columns={"territory_id": "region_id", "observation_year": "year",
                        "sector_id": "sector_a10", "sector_label": "sector_name"})
    out["sector_name"] = out["sector_a10"].map(SECTOR_LABELS_FR).fillna(out["sector_name"])
    return out[cols]


def build_pt_municipal_prediction_layer(pt_forecast: pd.DataFrame) -> pd.DataFrame:
    """Conform the PT municipal forecast (built separately, causal
    persistence/Ridge AR(1), observed panel, no proxy, no HPC) to the same
    unified prediction schema used by FR/NL, in French."""
    df = pt_forecast.copy()
    df["region_system"] = "MUNICIPALITY"
    df["sector_name"] = df["sector_id"].map(SECTOR_LABELS_FR)
    state_map = {"GROWTH": "Croissance", "DECLINE": "Recul", "STAGNATION": "Stable",
                 "insufficient_history": NO_DATA, "STRUCTURAL_ABSENT": PT_KZ_ABSENT}
    df["trend_state"] = df["economic_state"].map(state_map).fillna(NO_DATA)
    df["available"] = df["forecast_status"].eq("valid_forecast")
    df["forecast_evidence_tier"] = df["forecast_status"].map({
        "valid_forecast": "causal_persistence_or_ridge",
        "insufficient_history": "unavailable",
        "structural_absent": "structural_absence",
    })
    out = df.rename(columns={"territory_id": "region_id", "observation_year": "year",
                              "sector_id": "sector_a10"})
    cols = [
        "country", "region_id", "region_system", "sector_a10", "sector_name",
        "year", "observed_value", "expected_value", "difference",
        "trend_state", "forecast_method", "forecast_status",
        "forecast_evidence_tier", "available",
    ]
    return out[cols]


def build_prediction_layer(forecast: pd.DataFrame | None, pt_forecast: pd.DataFrame) -> pd.DataFrame:
    fr_nl = build_fr_nl_prediction_layer(forecast)
    pt = build_pt_municipal_prediction_layer(pt_forecast)
    unified = pd.concat([fr_nl, pt], ignore_index=True)
    # Fail-closed: PT/KZ must never be "available" in the unified view.
    pt_kz_mask = unified["country"].eq("PT") & unified["sector_a10"].eq("KZ")
    assert not unified.loc[pt_kz_mask, "available"].any(), \
        "FAIL_CLOSED: PT KZ must never be an available forecast"
    return unified


def build_map_state_by_year_sector(territory: pd.DataFrame) -> dict:
    df = territory.copy()
    df["state_human"] = df["state"].apply(human_state_fr)
    df["evidence_badge"] = df.apply(evidence_badge_for_territory_row, axis=1)
    out: dict = {}
    for (country, region_id), grp in df.groupby(["country", "region_id"], sort=False):
        region_id = str(region_id)
        out.setdefault(country, {})
        out[country].setdefault(region_id, {})
        for sector, grp_s in grp.groupby("sector_a10", sort=False):
            out[country][region_id].setdefault(sector, {})
            for _, row in grp_s.iterrows():
                state_human = row["state_human"]
                if country == "PT" and sector == "KZ":
                    state_human = PT_KZ_ABSENT
                out[country][region_id][sector][int(row["year"])] = [
                    state_human,
                    None if pd.isna(row["velocity"]) else round(float(row["velocity"]), 4),
                    None if pd.isna(row["value"]) else round(float(row["value"]), 3),
                    row["evidence_badge"],
                ]
    return out


def build_prediction_lookup_payload(prediction_view: pd.DataFrame) -> dict:
    """{country: {region_id: {sector: {year: [observed, expected, difference, trend_state]}}}}"""
    out: dict = {}
    df = prediction_view[prediction_view["available"]]
    for (country, region_id), grp in df.groupby(["country", "region_id"], sort=False):
        region_id = str(region_id)
        out.setdefault(country, {})
        out[country].setdefault(region_id, {})
        for sector, grp_s in grp.groupby("sector_a10", sort=False):
            out[country][region_id].setdefault(sector, {})
            for _, row in grp_s.iterrows():
                out[country][region_id][sector][int(row["year"])] = [
                    None if pd.isna(row["observed_value"]) else round(float(row["observed_value"]), 2),
                    None if pd.isna(row["expected_value"]) else round(float(row["expected_value"]), 2),
                    None if pd.isna(row["difference"]) else round(float(row["difference"]), 2),
                    row["trend_state"],
                ]
    return out


def build_relation_timeline(relation_view: pd.DataFrame) -> dict:
    all_windows = sorted(relation_view["window"].unique(), key=lambda w: int(w.split("-")[0]))
    edges = relation_view.to_dict(orient="records")
    by_window: dict = {w: [] for w in all_windows}
    for i, e in enumerate(edges):
        by_window[e["window"]].append(i)
    return {"windows": all_windows, "edges": edges, "edges_by_window": by_window}


def build_economic_basins(territory_view: pd.DataFrame) -> dict:
    """Part E — 'Bassins économiques' (economic concentration zones).

    For each (country, region, year), compute an intensity score from
    already-derived velocity/state (no new scientific number invented):
    score = mean velocity across observed sectors that year, mapped to a
    quantile bucket per country/year so the choropleth opacity/colour layer
    is comparable within a country-year slice. NEVER called a "causal
    cluster" — these are zones of similar dynamics, a descriptive grouping.
    """
    df = territory_view.copy()
    df = df[df["velocity"].notna()]
    agg = df.groupby(["country", "region_id", "year"], as_index=False)["velocity"].mean()
    agg = agg.rename(columns={"velocity": "intensity_score"})

    out: dict = {}
    for (country, year), grp in agg.groupby(["country", "year"]):
        if len(grp) < 2:
            quantile = pd.Series([0.5] * len(grp), index=grp.index)
        else:
            quantile = grp["intensity_score"].rank(pct=True)
        out.setdefault(country, {})
        out[country].setdefault(str(int(year)), {})
        for (region_id, score, q) in zip(grp["region_id"].astype(str), grp["intensity_score"], quantile):
            out[country][str(int(year))][region_id] = [round(float(score), 4), round(float(q), 4)]
    return out


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    src = load_sources()

    territory_view = build_territory_view(src["territory"])
    relation_view = build_relation_view(src["relation"])
    sector_view = build_sector_view(src["territory"])
    prediction_view = build_prediction_layer(src["forecast"], src["pt_municipal_forecast"])
    map_state = build_map_state_by_year_sector(src["territory"])
    relation_timeline = build_relation_timeline(relation_view)
    prediction_lookup = build_prediction_lookup_payload(prediction_view)
    economic_basins = build_economic_basins(territory_view)

    pt_kz_absent = pt_kz_structural_absent_flag(src["territory"])

    _atomic_write_df_csv(territory_view, OUT_DIR / "territory_view.csv")
    _atomic_write_text(OUT_DIR / "territory_view.json", territory_view.to_json(orient="records"))
    _atomic_write_df_csv(sector_view, OUT_DIR / "sector_view.csv")
    _atomic_write_text(OUT_DIR / "sector_view.json", sector_view.to_json(orient="records"))
    _atomic_write_df_csv(relation_view, OUT_DIR / "relation_view.csv")
    _atomic_write_text(OUT_DIR / "relation_view.json", relation_view.to_json(orient="records"))
    _atomic_write_df_csv(prediction_view, OUT_DIR / "prediction_view.csv")
    _atomic_write_text(OUT_DIR / "prediction_view.json", prediction_view.to_json(orient="records"))
    _atomic_write_text(OUT_DIR / "map_state_by_year_sector.json",
                        json.dumps(map_state, separators=(",", ":"), sort_keys=True))
    _atomic_write_text(OUT_DIR / "relation_timeline.json",
                        json.dumps(relation_timeline, separators=(",", ":"), sort_keys=True))
    _atomic_write_text(OUT_DIR / "prediction_lookup.json",
                        json.dumps(prediction_lookup, separators=(",", ":"), sort_keys=True))
    _atomic_write_text(OUT_DIR / "economic_basins.json",
                        json.dumps(economic_basins, separators=(",", ":"), sort_keys=True))

    blocked_copy_path = OUT_DIR / "blocked_proxy_edges_v04_copy.csv"
    _atomic_write_df_csv(src["blocked"], blocked_copy_path)

    output_files = {
        "territory_view.csv": territory_view,
        "sector_view.csv": sector_view,
        "relation_view.csv": relation_view,
        "prediction_view.csv": prediction_view,
        "blocked_proxy_edges_v04_copy.csv": src["blocked"],
    }
    checksums = {name: _sha256_file(OUT_DIR / name)[:16] for name in output_files}
    checksums["map_state_by_year_sector.json"] = _sha256_file(OUT_DIR / "map_state_by_year_sector.json")[:16]
    checksums["relation_timeline.json"] = _sha256_file(OUT_DIR / "relation_timeline.json")[:16]
    checksums["prediction_lookup.json"] = _sha256_file(OUT_DIR / "prediction_lookup.json")[:16]
    checksums["economic_basins.json"] = _sha256_file(OUT_DIR / "economic_basins.json")[:16]
    checksums["pt_municipal_prediction_view.csv"] = _sha256_file(PT_MUNICIPAL_PREDICTION_PATH)[:16]

    source_checksums = {
        "granular_territory_state_panel.csv": _sha256_file(TERRITORY_PATH)[:16],
        "granular_relation_edges.csv": _sha256_file(RELATION_PATH)[:16],
        "blocked_proxy_edges.csv": _sha256_file(BLOCKED_PATH)[:16],
        "pt_municipal_phase7_panel.csv": _sha256_file(
            REPO_ROOT / "data/processed/phase7_pt_municipal/pt_municipal_phase7_panel.csv")[:16],
    }
    if V03_PANEL_PATH.exists():
        source_checksums["herald_observatory_v03_panel.csv"] = _sha256_file(V03_PANEL_PATH)[:16]

    pt_pred = prediction_view[prediction_view["country"] == "PT"]
    pt_pred_status = "CLOSED" if (pt_pred["region_system"] == "MUNICIPALITY").all() and len(pt_pred) > 0 \
        else "NOT_INTEGRATED"

    manifest = {
        "version": "0.5.1",
        "name": "HERALD Observatory v0.5.1 — Narrative presentation layer (corrected)",
        "supersedes": "0.5 (OBSERVATORY_V05_PARTIAL — see HERALD_OBSERVATORY_V051_CORRECTION_AUDIT.md)",
        "generated_at": "STATIC",
        "dec_references": src["v04_manifest"].get("dec_references", []) + [
            "DEC-067_OBSERVATORY_V05_NARRATIVE", "OBSERVATORY_V051_CORRECTION"],
        "source_files": source_checksums,
        "output_files": checksums,
        "rules": {
            "nl_gemeente_proxy_relation_edges_forbidden": True,
            "nl_gemeente_proxy_allowed_in_territory_view": True,
            "blocked_proxy_edges_isolated": True,
            "pt_kz_structural_absent": bool(pt_kz_absent),
            "prediction_layer_countries": sorted(set(prediction_view["country"].unique())) if len(prediction_view) else [],
            "pt_municipal_prediction_status": pt_pred_status,
            "pt_municipal_prediction_method": "causal_persistence_or_ridge_ar1_on_observed_municipal_panel",
            "pt_municipal_prediction_note": (
                "PT municipal forecast generated via causal persistence/Ridge on observed "
                "municipal panel; no proxy, no HPC."
            ),
            "language": "fr",
        },
        "row_counts": {
            "territory_view": len(territory_view),
            "sector_view": len(sector_view),
            "relation_view": len(relation_view),
            "prediction_view": len(prediction_view),
            "prediction_view_pt_municipal": int((prediction_view["country"] == "PT").sum()),
            "blocked_proxy_edges_v04_copy": len(src["blocked"]),
        },
        "no_data_vocabulary": {
            "donnee_insuffisante": NO_DATA,
            "secteur_absent_portugal": PT_KZ_ABSENT,
            "proxy_territorial": PROXY_CONTEXT,
        },
    }
    manifest["generated_at"] = datetime.now(timezone.utc).isoformat()
    _atomic_write_text(OUT_DIR / "manifest.json", json.dumps(manifest, indent=2, sort_keys=True))

    logger.info("Wrote v0.5.1 narrative exports to %s", OUT_DIR)
    logger.info("territory_view=%d sector_view=%d relation_view=%d prediction_view=%d (PT municipal rows=%d)",
                len(territory_view), len(sector_view), len(relation_view), len(prediction_view),
                int((prediction_view["country"] == "PT").sum()))


if __name__ == "__main__":
    main()
