"""
Build the HERALD Observatory v0.5 narrative presentation-layer exports.

This module does NOT recompute, alter, or re-derive any scientific decision,
number, or label. It is a pure re-shaping / translation layer on top of the
already-validated v0.4 granular exports (territory state, relation edges,
blocked proxy edges) plus the v0.3 forecast columns (FR ZE2020 / NL COROP
only — see HERALD_OBSERVATORY_V05_PREDICTION_GAP.md for why PT is excluded
from the prediction layer at the municipal grain).

Hard rules enforced here (must not regress):
  - NL gemeente proxy (region_system=GEMEENTE_PROXY) NEVER enters
    relation_view / the main sector-to-sector graph dataset. It may only
    appear in territory_view, always carrying evidence_badge="proxy".
  - blocked_proxy_edges.csv (121 rows) is kept in its own file/dataset,
    never merged into relation_view.
  - PT KZ is marked structural_absent explicitly, never a bare NaN.
  - No raw "NaN" string is ever written into a *_view.csv/json human-facing
    field; numeric NaN remains valid inside numeric columns (pandas/JSON
    null), but text/label fields use the controlled vocabulary below.
  - No causal language is generated by this script.

Outputs (data/processed/herald_observatory_v05_narrative/):
  - territory_view.csv / .json
  - sector_view.csv / .json
  - relation_view.csv / .json
  - map_state_by_year_sector.json
  - relation_timeline.json
  - manifest.json
"""
from __future__ import annotations

import hashlib
import json
import logging
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger(__name__)

REPO_ROOT = Path(__file__).resolve().parents[3]
V04_DIR = REPO_ROOT / "data/processed/herald_observatory_v04_granular"
TERRITORY_PATH = V04_DIR / "granular_territory_state_panel.csv"
RELATION_PATH = V04_DIR / "granular_relation_edges.csv"
BLOCKED_PATH = V04_DIR / "blocked_proxy_edges.csv"
V04_MANIFEST_PATH = V04_DIR / "manifest.json"

V03_PANEL_PATH = REPO_ROOT / "data/processed/herald_observatory_v03/herald_observatory_v03_panel.csv"

OUT_DIR = REPO_ROOT / "data/processed/herald_observatory_v05_narrative"

SECTOR_LABELS = {
    "BE": "Industry and energy",
    "FZ": "Construction",
    "GI": "Trade, transport and hospitality",
    "JZ": "Information and communication",
    "KZ": "Financial and insurance activities",
    "LZ": "Real estate activities",
    "MN": "Professional and administrative services",
    "OQ": "Public administration, education and health",
    "RU": "Arts and other services",
}
SECTORS_ORDER = list(SECTOR_LABELS.keys())

# Controlled vocabulary — never display raw NaN to a layperson.
NO_DATA = "No evidence"
PT_KZ_ABSENT = "Sector not available for Portugal"
PROXY_CONTEXT = "Proxy / context (not relation evidence)"
INSUFFICIENT = "Insufficient evidence"

STATE_NUM = {"DECLINE": -1, "STAGNATION": 0, "GROWTH": 1}
STATE_LABEL_HUMAN = {1: "Growing", 0: "Stable", -1: "Falling", None: NO_DATA}

# region_system that matches v0.4 granular grain <-> v0.3 forecast grain
# (PT is excluded: v0.3 forecasts are at NUTS3 (25 coarse territories),
#  v0.4 granular state is at MUNICIPALITY (278 fine territories) — different
#  grains, cannot be joined without re-deriving a forecast that does not
#  exist today. See HERALD_OBSERVATORY_V05_PREDICTION_GAP.md.)
PREDICTION_JOINABLE_SYSTEMS = {"ZE2020", "COROP"}


def _sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def _atomic_write_text(path: Path, text: str) -> None:
    tmp = Path(str(path) + ".tmp")
    tmp.write_text(text, encoding="utf-8")
    tmp.replace(path)


def _atomic_write_df_csv(df: pd.DataFrame, path: Path) -> None:
    tmp = Path(str(path) + ".tmp")
    df.to_csv(tmp, index=False)
    tmp.replace(path)


def load_sources() -> dict:
    territory = pd.read_csv(TERRITORY_PATH, low_memory=False)
    relation = pd.read_csv(RELATION_PATH)
    blocked = pd.read_csv(BLOCKED_PATH)
    v04_manifest = json.loads(V04_MANIFEST_PATH.read_text())

    # Fail-closed invariants inherited from v0.4 — re-asserted here because
    # this builder reads the same raw inputs and must never let a future
    # change silently leak proxy data into the narrative relation view.
    assert "GEMEENTE_PROXY" not in relation["region_system"].values, \
        "FAIL_CLOSED: NL gemeente proxy must never appear in relation edges (v0.5 narrative)"
    assert (blocked["allowed_for_training_label"] == False).all(), \
        "FAIL_CLOSED: blocked proxy edges must have allowed_for_training_label=false"

    forecast = None
    if V03_PANEL_PATH.exists():
        forecast = pd.read_csv(V03_PANEL_PATH, low_memory=False)
    else:
        logger.warning("v0.3 panel not found at %s — prediction layer will be empty", V03_PANEL_PATH)

    return {
        "territory": territory, "relation": relation, "blocked": blocked,
        "v04_manifest": v04_manifest, "forecast": forecast,
    }


def human_state(state_str) -> str:
    if pd.isna(state_str):
        return NO_DATA
    return {"GROWTH": "Growing", "DECLINE": "Falling", "STAGNATION": "Stable",
            "INSUFFICIENT_DATA": NO_DATA}.get(state_str, NO_DATA)


def evidence_badge_for_territory_row(row) -> str:
    if row["evidence_type"] == "proxy_disaggregated_by_stock_share":
        return "Proxy / context"
    return "Observed"


def build_territory_view(territory: pd.DataFrame) -> pd.DataFrame:
    df = territory.copy()
    # region_name is empty for NL/PT rows at source (names are resolved from
    # geometry properties at render time in the dashboard) — never leave a
    # bare NaN in an exported text field, fall back to the region_id.
    df["region_name"] = df["region_name"].fillna(df["region_id"].astype(str))
    df["sector_name"] = df["sector_a10"].map(SECTOR_LABELS)
    df["state_human"] = df["state"].apply(human_state)
    df["evidence_badge"] = df.apply(evidence_badge_for_territory_row, axis=1)
    df["is_proxy_context"] = df["evidence_type"].eq("proxy_disaggregated_by_stock_share")

    # PT structural_absent KZ (DEC-064/DEC-018): KZ is unobservable for
    # Portugal, not merely missing for some rows — every PT/KZ row carries
    # state=INSUFFICIENT_DATA with no value. Relabel explicitly so the
    # dashboard never shows a bare "no evidence"/NaN for this case; it must
    # read as "not available for Portugal", a structural fact, not a gap.
    pt_kz_mask = df["country"].eq("PT") & df["sector_a10"].eq("KZ")
    if pt_kz_mask.any():
        df.loc[pt_kz_mask, "state_human"] = PT_KZ_ABSENT
        df.loc[pt_kz_mask, "evidence_badge"] = "Structurally absent"

    out_cols = [
        "country", "region_id", "region_name", "region_system", "year",
        "sector_a10", "sector_name", "value", "state", "state_human",
        "velocity", "evidence_type", "evidence_badge", "is_proxy_context",
        "source_table", "allowed_use",
    ]
    return df[out_cols]


def pt_kz_structural_absent_flag(territory: pd.DataFrame) -> bool:
    """True if PT/KZ is structurally absent: either no KZ rows exist at all,
    or every KZ row for PT carries no observed value (100% NaN value / state
    always INSUFFICIENT_DATA) — confirmed pattern per DEC-064
    (reports/HERALD_DEC064_PT_MUNICIPAL_PHASE7_AUDIT.md: 'KZ structural_absent
    ... No KZ claims'). This is NOT a per-row missing-data case; it is the
    sector itself being unobservable for Portugal (per DEC-018)."""
    pt_kz = territory[(territory["country"] == "PT") & (territory["sector_a10"] == "KZ")]
    if len(pt_kz) == 0:
        return True
    return bool(pt_kz["value"].isna().all())


def build_relation_view(relation: pd.DataFrame) -> pd.DataFrame:
    df = relation.copy()
    assert "GEMEENTE_PROXY" not in df["region_system"].values
    df["source_sector_name"] = df["source_sector"].map(SECTOR_LABELS)
    df["target_sector_name"] = df["target_sector"].map(SECTOR_LABELS)
    df["direction_human"] = df["sign"].map({
        "+": "moves in the same direction",
        "-": "moves in the opposite direction",
    })
    df["window_start"] = df["window"].str.split("-").str[0].astype(int)
    df["window_end"] = df["window"].str.split("-").str[1].astype(int)

    evidence_badge_map = {
        "ROBUST_ORIGINAL": "Robust",
        "FINE_GRAIN_SUPPORTED": "Supported",
        "EXPLORATORY_FINE_GRAIN": "Exploratory",
    }
    df["evidence_badge"] = df["label_class"].map(evidence_badge_map).fillna(INSUFFICIENT)

    group_cols = ["country", "source_sector", "target_sector"]
    counts = df.groupby(group_cols)["window"].nunique().rename("n_windows")
    signs = df.groupby(group_cols)["sign"].nunique().rename("n_distinct_signs")
    df = df.merge(counts, on=group_cols, how="left").merge(signs, on=group_cols, how="left")
    df["is_recurring"] = df["n_windows"] >= 2
    df["sign_changes"] = df["n_distinct_signs"] >= 2
    df = df.drop(columns=["n_distinct_signs"])

    def sentence(row) -> str:
        return (
            f"Between {row['window_start']} and {row['window_end']}, in "
            f"{row['country']}, {row['source_sector_name']} ({row['source_sector']}) "
            f"{row['direction_human']} as {row['target_sector_name']} ({row['target_sector']}). "
            f"This is observed evidence, not proof of causality."
        )
    df["plain_sentence"] = df.apply(sentence, axis=1)
    return df


def build_sector_view(territory: pd.DataFrame) -> pd.DataFrame:
    """Per country x sector x year aggregate, used by the sector layer panel
    when a territory is clicked (top sectors, time series, growth/decline
    state) without re-deriving any number — pure groupby of already-computed
    state/velocity."""
    df = territory.copy()
    df["state_num"] = df["state"].map(STATE_NUM)
    grp = df.groupby(["country", "sector_a10", "year"], as_index=False).agg(
        n_territories=("region_id", "nunique"),
        n_growth=("state_num", lambda s: (s == 1).sum()),
        n_decline=("state_num", lambda s: (s == -1).sum()),
        n_stable=("state_num", lambda s: (s == 0).sum()),
        n_no_data=("state_num", lambda s: s.isna().sum()),
        mean_velocity=("velocity", "mean"),
    )
    grp["sector_name"] = grp["sector_a10"].map(SECTOR_LABELS)
    grp["structural_absent"] = False
    pt_kz_mask = grp["country"].eq("PT") & grp["sector_a10"].eq("KZ")
    grp.loc[pt_kz_mask, "structural_absent"] = True
    return grp


def build_prediction_layer(forecast: pd.DataFrame | None) -> pd.DataFrame:
    """Standardized observed-vs-expected view, ONLY for the country/region
    systems where v0.3 forecast grain matches v0.4 granular grain (FR
    ZE2020, NL COROP). PT is intentionally excluded here — see
    HERALD_OBSERVATORY_V05_PREDICTION_GAP.md. Never fabricates a number."""
    if forecast is None:
        return pd.DataFrame(columns=[
            "country", "territory_id", "sector_id", "year", "observed_value",
            "expected_value", "difference", "trend_state", "available",
        ])
    df = forecast[forecast["region_system"].isin(PREDICTION_JOINABLE_SYSTEMS)].copy()
    df["expected_value"] = df["ridge_forecast"]
    df["expected_value"] = df["expected_value"].fillna(df["persistence_forecast"])
    df["difference"] = df["observed_value"] - df["expected_value"]
    df["trend_state"] = df["economic_state"].fillna(INSUFFICIENT)
    df["available"] = df["expected_value"].notna()
    out = df[[
        "country", "territory_id", "region_system", "sector_id", "sector_label",
        "observation_year", "observed_value", "expected_value", "difference",
        "trend_state", "forecast_method", "forecast_evidence_tier", "available",
    ]].rename(columns={"territory_id": "region_id", "observation_year": "year",
                        "sector_id": "sector_a10", "sector_label": "sector_name"})
    return out


def build_map_state_by_year_sector(territory: pd.DataFrame) -> dict:
    """{country: {region_id: {sector: {year: [state_human, velocity, value, evidence_badge]}}}}
    — the structure the dynamic choropleth needs to recolor instantly on
    year/sector change without a server round-trip. This *is* the heatmap:
    the map itself changes color, there is no separate heatmap widget.
    Compact array form (not a dict per cell) keeps the embedded payload
    small at 142k+ rows."""
    df = territory.copy()
    df["state_human"] = df["state"].apply(human_state)
    df["evidence_badge"] = df.apply(evidence_badge_for_territory_row, axis=1)
    out: dict = {}
    for (country, region_id), grp in df.groupby(["country", "region_id"], sort=False):
        region_id = str(region_id)
        out.setdefault(country, {})
        out[country].setdefault(region_id, {})
        for sector, grp_s in grp.groupby("sector_a10", sort=False):
            out[country][region_id].setdefault(sector, {})
            for _, row in grp_s.iterrows():
                state_human = row["state_human"]
                if country == "PT" and sector == "KZ":
                    state_human = PT_KZ_ABSENT
                out[country][region_id][sector][int(row["year"])] = [
                    state_human,
                    None if pd.isna(row["velocity"]) else round(float(row["velocity"]), 4),
                    None if pd.isna(row["value"]) else round(float(row["value"]), 3),
                    row["evidence_badge"],
                ]
    return out


def build_relation_timeline(relation_view: pd.DataFrame) -> dict:
    """{window: [edge_index,...]} plus the flat edge list, used to drive the
    timeline slider / play mode and the persistent-mode (all faint, active
    window highlighted) rendering."""
    all_windows = sorted(relation_view["window"].unique(), key=lambda w: int(w.split("-")[0]))
    edges = relation_view.to_dict(orient="records")
    by_window: dict = {w: [] for w in all_windows}
    for i, e in enumerate(edges):
        by_window[e["window"]].append(i)
    return {"windows": all_windows, "edges": edges, "edges_by_window": by_window}


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    src = load_sources()

    territory_view = build_territory_view(src["territory"])
    relation_view = build_relation_view(src["relation"])
    sector_view = build_sector_view(src["territory"])
    prediction_view = build_prediction_layer(src["forecast"])
    map_state = build_map_state_by_year_sector(src["territory"])
    relation_timeline = build_relation_timeline(relation_view)

    pt_kz_absent = pt_kz_structural_absent_flag(src["territory"])

    _atomic_write_df_csv(territory_view, OUT_DIR / "territory_view.csv")
    _atomic_write_text(OUT_DIR / "territory_view.json",
                        territory_view.to_json(orient="records"))
    _atomic_write_df_csv(sector_view, OUT_DIR / "sector_view.csv")
    _atomic_write_text(OUT_DIR / "sector_view.json", sector_view.to_json(orient="records"))
    _atomic_write_df_csv(relation_view, OUT_DIR / "relation_view.csv")
    _atomic_write_text(OUT_DIR / "relation_view.json", relation_view.to_json(orient="records"))
    _atomic_write_df_csv(prediction_view, OUT_DIR / "prediction_view.csv")
    _atomic_write_text(OUT_DIR / "prediction_view.json", prediction_view.to_json(orient="records"))
    _atomic_write_text(OUT_DIR / "map_state_by_year_sector.json",
                        json.dumps(map_state, separators=(",", ":"), sort_keys=True))
    _atomic_write_text(OUT_DIR / "relation_timeline.json",
                        json.dumps(relation_timeline, separators=(",", ":"), sort_keys=True))

    # blocked edges are copied verbatim (not regenerated) to the v05 dir so
    # the dashboard/tests have a single source directory to read from, but
    # the original v0.4 file remains the canonical source (never altered).
    blocked_copy_path = OUT_DIR / "blocked_proxy_edges_v04_copy.csv"
    _atomic_write_df_csv(src["blocked"], blocked_copy_path)

    output_files = {
        "territory_view.csv": territory_view,
        "sector_view.csv": sector_view,
        "relation_view.csv": relation_view,
        "prediction_view.csv": prediction_view,
        "blocked_proxy_edges_v04_copy.csv": src["blocked"],
    }
    checksums = {name: _sha256_file(OUT_DIR / name)[:16] for name in output_files}
    checksums["map_state_by_year_sector.json"] = _sha256_file(OUT_DIR / "map_state_by_year_sector.json")[:16]
    checksums["relation_timeline.json"] = _sha256_file(OUT_DIR / "relation_timeline.json")[:16]

    source_checksums = {
        "granular_territory_state_panel.csv": _sha256_file(TERRITORY_PATH)[:16],
        "granular_relation_edges.csv": _sha256_file(RELATION_PATH)[:16],
        "blocked_proxy_edges.csv": _sha256_file(BLOCKED_PATH)[:16],
    }
    if V03_PANEL_PATH.exists():
        source_checksums["herald_observatory_v03_panel.csv"] = _sha256_file(V03_PANEL_PATH)[:16]

    manifest = {
        "version": "0.5",
        "name": "HERALD Observatory v0.5 — Narrative presentation layer",
        "generated_at": "STATIC",  # overwritten below only for human info, not used in checksums
        "dec_references": src["v04_manifest"].get("dec_references", []) + ["DEC-067_OBSERVATORY_V05_NARRATIVE"],
        "source_files": source_checksums,
        "output_files": checksums,
        "rules": {
            "nl_gemeente_proxy_relation_edges_forbidden": True,
            "nl_gemeente_proxy_allowed_in_territory_view": True,
            "blocked_proxy_edges_isolated": True,
            "pt_kz_structural_absent": bool(pt_kz_absent),
            "prediction_layer_countries": sorted(set(prediction_view["country"].unique())) if len(prediction_view) else [],
            "prediction_layer_excludes_pt_reason": "v0.3 forecast grain is PT NUTS3 (25 coarse territories); "
                "v0.4 granular state is PT MUNICIPALITY (278 fine territories) — different grains, no validated "
                "join exists. See reports/HERALD_OBSERVATORY_V05_PREDICTION_GAP.md.",
        },
        "row_counts": {
            "territory_view": len(territory_view),
            "sector_view": len(sector_view),
            "relation_view": len(relation_view),
            "prediction_view": len(prediction_view),
            "blocked_proxy_edges_v04_copy": len(src["blocked"]),
        },
        "no_data_vocabulary": {
            "no_evidence": NO_DATA,
            "pt_kz_structural_absent": PT_KZ_ABSENT,
            "proxy_context": PROXY_CONTEXT,
            "insufficient_evidence": INSUFFICIENT,
        },
    }
    manifest["generated_at"] = datetime.now(timezone.utc).isoformat()
    _atomic_write_text(OUT_DIR / "manifest.json", json.dumps(manifest, indent=2, sort_keys=True))

    logger.info("Wrote v0.5 narrative exports to %s", OUT_DIR)
    logger.info("territory_view=%d sector_view=%d relation_view=%d prediction_view=%d",
                len(territory_view), len(sector_view), len(relation_view), len(prediction_view))


if __name__ == "__main__":
    main()
